import { env } from "cloudflare:workers";
import { approveAgentRun, saveAgentRun, type AgentResult } from "@/db/agents";
const prompts:Record<string,string>={"Idea Validation":"Evaluate pain, urgency, differentiation, feasibility, market access, and willingness to pay.","AI Mediation":"Act as a neutral workplace mediator. Separate facts, positions, interests, and shared goals. Do not make employment decisions.","Governance Agents":"Review finance, compliance, delivery, and people risk with accountable, approval-gated actions.","Financial Dashboard":"Use verified context: MRR $84,240; net burn $41,800; cash $593,400; runway 14.2 months. Never invent balances.","Term Sheet Analyzer":"Analyze economics, dilution, liquidation preference, anti-dilution, board control, protective provisions, and founder risk. This is not legal advice."};
const base={confidence:78,evidence:["User-provided operating context"],assumptions:["Inputs are current and complete"],risks:["External data has not been independently verified"],metrics:[{label:"Evidence coverage",value:"Medium",source:"Northstar rubric"}],mode:"demo" as const};
const demo:Record<string,Omit<AgentResult,"runId">>={
"Idea Validation":{...base,score:"82",title:"Promising—validate willingness to pay",summary:"The problem is focused and the wedge is credible. Payment evidence is the main uncertainty.",items:["Interview 8 target customers","Run a paid concierge pilot","Measure weekly time saved"],evidence:["Target customer and recurring pain were described"],assumptions:["The buyer owns a software budget"],risks:["No observed payment behavior","Alternatives were not supplied"],metrics:[{label:"Problem urgency",value:"High",source:"User input"},{label:"Evidence coverage",value:"58%",source:"Northstar rubric"}]},
"AI Mediation":{...base,score:"91",title:"Shared outcome identified",summary:"The disagreement concerns risk ownership more than the desired outcome.",items:["Define non-negotiable checks","Reduce scope to critical workflows","Write a go/no-go rubric"],evidence:["Both positions reference the same outcome"],assumptions:["Both parties provided full context"],risks:["Power imbalance may be hidden","Private HR facts may be missing"]},
"Governance Agents":{...base,score:"4",title:"Governance review completed",summary:"No critical breach was identified; two decisions need accountable owners.",items:["Assign the launch risk owner","Complete the policy review","Record hiring approval"],evidence:["Four operating areas reviewed"],risks:["Policy review overdue","Delivery ownership unclear"]},
"Financial Dashboard":{...base,score:"16",confidence:88,title:"Scenario remains inside the safety threshold",summary:"The plan is affordable if cost is capped and the second commitment follows the next major close.",items:["Stage the second hire","Cap incremental cost","Reforecast if conversion falls"],evidence:["Cash $593,400","Net burn $41,800/month"],assumptions:["Revenue remains stable","Incremental cost stays below $25k/month"],risks:["Pipeline timing uncertainty","Tax reserve excluded"],metrics:[{label:"Current runway",value:"14.2 months",source:"Finance context"},{label:"Scenario runway",value:"11.8 months",source:"Deterministic calculation"}]},
"Term Sheet Analyzer":{...base,score:"B+",title:"Standard economics, moderate control risk",summary:"The preference looks conventional. Board composition and protective provisions need counsel review.",items:["Clarify option-pool treatment","Narrow investor vetoes","Request a founder cure period"],evidence:["1x non-participating preference","Weighted-average anti-dilution"],assumptions:["No side letter changes the terms"],risks:["Board control unspecified","Option-pool treatment unclear"]}};
type ResponsesPayload={output?:Array<{content?:Array<{type?:string;text?:string}>}>};function outputText(p:ResponsesPayload){for(const i of p.output||[])for(const c of i.content||[])if(c.type==="output_text"&&c.text)return c.text;return "";}
const schema={type:"object",properties:{score:{type:"string"},confidence:{type:"number"},title:{type:"string"},summary:{type:"string"},items:{type:"array",items:{type:"string"},minItems:3,maxItems:7},evidence:{type:"array",items:{type:"string"},minItems:1,maxItems:8},assumptions:{type:"array",items:{type:"string"},minItems:1,maxItems:8},risks:{type:"array",items:{type:"string"},minItems:1,maxItems:8},metrics:{type:"array",items:{type:"object",properties:{label:{type:"string"},value:{type:"string"},source:{type:"string"}},required:["label","value","source"],additionalProperties:false},maxItems:8}},required:["score","confidence","title","summary","items","evidence","assumptions","risks","metrics"],additionalProperties:false};
export async function POST(request:Request){try{const email=request.headers.get("x-demo-email");if(!email)return Response.json({error:"Authentication required"},{status:401});const body=await request.json() as {agent?:string;input?:string;approveRunId?:string};if(body.approveRunId)return Response.json({approved:await approveAgentRun(email,body.approveRunId)});if(!body.agent||!prompts[body.agent]||!body.input?.trim())return Response.json({error:"Agent and input are required"},{status:400});const runtime=env as unknown as {OPENAI_API_KEY?:string;OPENAI_MODEL?:string};let result:Omit<AgentResult,"runId">;if(!runtime.OPENAI_API_KEY)result=demo[body.agent];else{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${runtime.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:runtime.OPENAI_MODEL||"gpt-5.6-sol",instructions:`You are Northstar's ${body.agent}. ${prompts[body.agent]} Produce a detailed decision report. Separate evidence, assumptions, risks, metrics, and actions. Never present assumptions as facts.`,input:body.input,text:{format:{type:"json_schema",name:"agent_result",strict:true,schema}}})});if(!response.ok)throw new Error(`OpenAI request failed (${response.status})`);result={...JSON.parse(outputText(await response.json())),mode:"live"};}const runId=await saveAgentRun(email,body.agent,body.input,result);return Response.json({...result,runId});}catch(error){return Response.json({error:error instanceof Error?error.message:"Agent failed"},{status:500});}}
