"use client";

export function LandingPage({onGetStarted}:{onGetStarted:()=>void}){
  return <main className="landing-page"><header className="landing-nav"><a className="landing-brand" href="#top"><span>N</span><b>northstar</b></a><nav aria-label="Landing navigation"><a href="#platform">Platform</a><a href="#workflow">How it works</a><a href="#security">Security</a></nav><div><button className="landing-login" onClick={onGetStarted}>Sign in</button><button className="landing-cta" onClick={onGetStarted}>Enter workspace <span>→</span></button></div></header><section className="landing-hero" id="top"><div className="hero-copy"><span className="landing-kicker"><i/> THE OPERATING SYSTEM FOR AMBITIOUS STARTUPS</span><h1>Run your company with <em>clarity.</em></h1><p>Northstar connects strategy, revenue, people, finance, and decisions in one calm operating system—so your team knows what matters and moves together.</p><div className="hero-actions"><button className="landing-cta large" onClick={onGetStarted}>Start operating <span>→</span></button><a href="#platform">Explore the platform</a></div><div className="hero-proof"><span>Built for founders</span><span>Upgrade-safe customization</span><span>Private team workspaces</span></div></div><div className="product-window"><div className="window-top"><span/><span/><span/><b>Arc Labs · Operating picture</b></div><div className="window-body"><aside><strong>N</strong>{["⌂","✦","◎","◇","◉","▥"].map(icon=><i key={icon}>{icon}</i>)}</aside><section><div className="window-heading"><div><small>FRIDAY OPERATING REVIEW</small><h3>Good morning, Vijetha.</h3></div><span>82 <small>/100</small></span></div><div className="window-metrics"><article><small>Monthly revenue</small><b>$84.2k</b><em>+12.4%</em></article><article><small>Cash runway</small><b>14.2 mo</b><em>Healthy</em></article><article><small>Active pipeline</small><b>$312k</b><em>+8 deals</em></article></div><div className="window-brief"><span>✦</span><div><small>NORTHSTAR BRIEFING</small><b>Strong growth. One execution risk needs a decision.</b><p>The enterprise launch now blocks three high-intent deals. Assigning a reviewer today protects the August target.</p></div></div><div className="window-rows"><span/><span/><span/></div></section></div></div></section><section className="landing-trust"><span>STRATEGY</span><span>REVENUE</span><span>PEOPLE</span><span>FINANCE</span><span>GOVERNANCE</span><span>AUTOMATION</span></section><section className="landing-platform" id="platform"><div className="section-heading"><span>ONE CONNECTED COMPANY</span><h2>Less dashboard. More direction.</h2><p>Every module shares the same company context, permissions, and operating rhythm.</p></div><div className="platform-grid">{[
    ["01","Operating overview","See health, priorities, risks, runway, and pipeline before the day begins."],
    ["02","Goals & execution","Turn strategy into owned outcomes with progress, due dates, and blockers."],
    ["03","Team collaboration","Share updates, decisions, comments, and wins inside a private company feed."],
    ["04","Guardrailed automation","Describe business rules in plain English and generate upgrade-safe workflows."],
    ["05","Decision intelligence","Validate ideas, model financial scenarios, mediate conflict, and review terms."],
    ["06","Access & accountability","Invite your team and assign Owner, Leader, Member, or Viewer permissions."],
  ].map(([number,title,copy])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p><a onClick={onGetStarted}>Open module →</a></article>)}</div></section><section className="landing-flow" id="workflow"><div><span>FROM SIGNAL TO ACTION</span><h2>Your operating rhythm, built in.</h2><p>Northstar turns scattered company activity into a reliable daily system.</p></div><ol>{[["01","Connect","Bring goals, pipeline, team, and finance into one workspace."],["02","Understand","See evidence, assumptions, risks, and the decisions that need attention."],["03","Act","Assign owners, automate workflows, approve recommendations, and track outcomes."]].map(([n,title,copy])=><li key={n}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol></section><section className="landing-security" id="security"><div><span className="security-mark">✓</span><div><small>BUILT FOR RESPONSIBLE OPERATIONS</small><h2>Customize without compromising the core.</h2><p>The four-level Guardrail Engine keeps configuration and automation upgrade-safe, isolates extensions, and blocks risky core modifications by default.</p></div></div><div className="security-stats"><article><b>100%</b><span>safe configuration</span></article><article><b>0</b><span>core files modified</span></article><article><b>1-click</b><span>version rollback</span></article></div></section><section className="landing-final"><span>NORTHSTAR</span><h2>A clearer company starts with one workspace.</h2><p>Give your team the context, tools, and accountability to do their best work.</p><button className="landing-cta large" onClick={onGetStarted}>Enter Northstar <span>→</span></button></section><footer className="landing-footer"><a className="landing-brand" href="#top"><span>N</span><b>northstar</b></a><p>Startup Operating System · Built for ambitious teams.</p><button onClick={onGetStarted}>Sign in</button></footer></main>;
}
