"use client";

import { useEffect, useMemo, useState } from "react";
import type { DashboardData } from "@/db/bootstrap";

const navItems = ["Overview", "Feed", "Idea Validation", "AI Mediation", "Governance Agents", "Financial Dashboard", "Term Sheet Analyzer", "Goals", "CRM", "People", "Team", "Team Access", "Reports", "Settings"] as const;
const icons: Record<string, string> = { Overview:"⌂",Feed:"◫", "Idea Validation":"✦", "AI Mediation":"⇄", "Governance Agents":"⬡", "Financial Dashboard":"▥", "Term Sheet Analyzer":"§", Goals:"◎", CRM:"◇", People:"◉", Team:"◌", "Team Access":"♙", Reports:"▤", Settings:"⚙" };

export function StartupOS({ user, onSignOut }: { user?: { name: string; email: string }; onSignOut?: () => void }) {
  const [data, setData] = useState<DashboardData | null>(null);
  const [active, setActive] = useState<(typeof navItems)[number]>("Overview");
  const [loadingId, setLoadingId] = useState<number | null>(null);
  const [error, setError] = useState("");
  const [query, setQuery] = useState("");
  const [answer, setAnswer] = useState("");
  const [menuOpen, setMenuOpen] = useState(false);

  async function load() {
    try {
      const response = await fetch("/api/dashboard");
      if (!response.ok) throw new Error("Could not connect to the operating data");
      setData(await response.json());
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Something went wrong"); }
  }
  useEffect(() => {
    const savedTheme = window.localStorage.getItem("northstar-theme");
    document.documentElement.dataset.theme = savedTheme === "dark" ? "dark" : "light";
    fetch("/api/dashboard")
      .then((response) => {
        if (!response.ok) throw new Error("Could not connect to the operating data");
        return response.json() as Promise<DashboardData>;
      })
      .then(setData)
      .catch((caught: unknown) => setError(caught instanceof Error ? caught.message : "Something went wrong"));
  }, []);

  function toggleTheme() {
    const nextTheme = document.documentElement.dataset.theme === "dark" ? "light" : "dark";
    document.documentElement.dataset.theme = nextTheme;
    window.localStorage.setItem("northstar-theme", nextTheme);
  }
  const pending = useMemo(() => data?.insights.filter((item) => item.status === "pending") ?? [], [data]);

  async function approve(id: number) {
    setLoadingId(id); setError("");
    try {
      const response = await fetch("/api/dashboard", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ insightId: id }) });
      if (!response.ok) throw new Error("The action could not be approved");
      setData(await response.json());
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Something went wrong"); }
    finally { setLoadingId(null); }
  }

  function askNorthstar(event: React.FormEvent) {
    event.preventDefault(); if (!query.trim()) return;
    const lower = query.toLowerCase();
    if (lower.includes("risk") || lower.includes("block")) setAnswer("The enterprise workspace launch is the highest-leverage risk. It is blocking $96k in pipeline and needs security review ownership today.");
    else if (lower.includes("revenue") || lower.includes("sales")) setAnswer("Revenue is up 12.4% to $84.2k MRR. The strongest near-term upside is Acme's annual contract plus a Northwind expansion conversation.");
    else if (lower.includes("team") || lower.includes("capacity")) setAnswer("Team velocity is 87%. Platform capacity will drop 22% next sprint; moving one roadmap item and borrowing a reviewer will protect the launch date.");
    else setAnswer("Your company is healthy overall: revenue and runway are strong, but the enterprise launch is the priority because it connects product execution directly to three open deals.");
  }

  if (!data) return <LoadingState error={error} retry={load} />;
  return <main className="app-shell">
    <aside className={menuOpen ? "sidebar open" : "sidebar"}>
      <div className="brand"><span className="brand-mark">N</span><span>northstar</span></div>
      <div className="workspace"><span className="avatar small">A</span><span><b>Arc Labs</b><small>Growth workspace</small></span><span className="chevron">⌄</span></div>
      <nav aria-label="Main navigation"><p className="nav-label">Workspace</p>{navItems.map((item) => <button key={item} className={active === item ? "nav-item active" : "nav-item"} onClick={() => { setActive(item); setMenuOpen(false); }}><span>{icons[item]}</span>{item}{item === "Overview" && pending.length ? <em>{pending.length}</em> : null}</button>)}</nav>
      <div className="sidebar-bottom"><button className="profile profile-button" onClick={()=>setActive("Settings")}><span className="avatar">{user?.name?.slice(0,2).toUpperCase() || "VS"}</span><span><b>{user?.name || "Vijetha"}</b><small>{user?.email || "Founder · Admin"}</small></span><span className="status-dot" /></button></div>
    </aside>
    <section className="main-area">
      <header className="topbar"><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">☰</button><div className="breadcrumb"><span>Arc Labs</span><b>/</b><strong>{active}</strong></div><div className="top-actions"><button className="theme-button" onClick={toggleTheme} aria-label="Switch light or dark mode">◐</button><button className="icon-button" aria-label="Notifications">♢<i>{pending.length}</i></button><button className="primary-button" onClick={() => document.getElementById("ask-input")?.focus()}>✦ Ask Northstar</button><button className="signout-button" onClick={onSignOut}>Sign out</button></div></header>
      <div className="content">{active === "Overview" ? <Overview data={data} pending={pending} approve={approve} loadingId={loadingId} query={query} setQuery={setQuery} answer={answer} ask={askNorthstar} onNavigate={setActive} /> : active === "Feed" ? <FeedPage user={user!}/> : active === "People" ? <PeoplePage user={user!}/> : active === "Team Access" ? <TeamAccessPage user={user!}/> : active === "Settings" ? <SettingsPage user={user!} onSaved={(next)=>{window.localStorage.setItem("northstar-demo-session",JSON.stringify(next));window.dispatchEvent(new Event("northstar-session-change"));}}/> : ["Idea Validation","AI Mediation","Governance Agents","Financial Dashboard","Term Sheet Analyzer"].includes(active) ? <IntelligenceModule active={active} user={user!}/> : <ModulePage active={active} data={data} user={user!} />}{error ? <div className="toast" role="alert">{error}</div> : null}</div>
    </section>
  </main>;
}

function LoadingState({ error, retry }: { error: string; retry: () => void }) {
  return <main className="loading-screen"><div className="loading-orbit"><span>N</span></div><h1>Aligning your company data</h1><p>{error || "Northstar is preparing today's operating picture…"}</p>{error ? <button className="primary-button" onClick={retry}>Try again</button> : <div className="loading-line"><i /></div>}</main>;
}

type OverviewProps = { data: DashboardData; pending: DashboardData["insights"]; approve: (id: number) => void; loadingId: number | null; query: string; setQuery: (value: string) => void; answer: string; ask: (event: React.FormEvent) => void; onNavigate:(item:(typeof navItems)[number])=>void };
function Overview({ data, pending, approve, loadingId, query, setQuery, answer, ask, onNavigate }: OverviewProps) {
  return <>
    <section className="odoo-launcher"><div className="launcher-title"><div><span className="eyebrow">YOUR COMPANY</span><h2>Good morning, Vijetha</h2></div><button aria-label="Customize apps">⋮</button></div><div className="odoo-app-grid">{[
      ["Idea Validation","✦","Validate ideas","#875A7B"],["AI Mediation","⇄","Resolve conflicts","#00A09D"],["Governance Agents","⬡","Governance","#E46F78"],["Financial Dashboard","▥","Live finance","#5C7CFA"],["Term Sheet Analyzer","§","Review terms","#F5A623"],["CRM","↗","Pipeline","#687D8F"]
    ].map(([name,icon,label,color])=><button key={name} onClick={()=>onNavigate(name as (typeof navItems)[number])}><span className="odoo-app-icon" style={{background:color}}>{icon}<i>{name==="CRM"?"4":name==="People"?"2":""}</i></span><b>{name}</b><small>{label}</small></button>)}</div></section>
    <section className="page-heading"><div><span className="eyebrow"><i /> LIVE OPERATING PICTURE</span><h1>Good morning, Vijetha.</h1><p>Here’s what needs your attention across Arc Labs today.</p></div><div className="date-chip"><span>FRI</span><b>31</b><small>July 2026</small></div></section>
    <section className="briefing-card"><div className="briefing-glow"/><div className="ai-orb">✦</div><div className="briefing-copy"><span className="eyebrow violet">NORTHSTAR DAILY BRIEFING</span><h2>Strong growth. One execution risk needs a decision.</h2><p>Revenue momentum is healthy and runway remains comfortable. The enterprise workspace launch is six days behind and now blocks three deals worth <strong>$96k</strong>. Reassigning a security reviewer today protects the August 8 launch.</p><div className="briefing-meta"><span><i className="pulse"/> Updated 4 min ago</span><button onClick={() => document.getElementById("ask-input")?.focus()}>Explore analysis →</button></div></div><div className="health-score"><div><span>82</span><small>/100</small></div><b>Company health</b><em>Healthy</em></div></section>
    <section className="metric-grid">{data.metrics.slice(0,3).map((metric) => <article className="metric-card" key={metric.id}><div className="metric-top"><span>{metric.label}</span><em className={metric.tone}>{metric.change}</em></div><h3>{metric.value}</h3><div className="progress-track"><i style={{ width: `${metric.progress}%` }}/></div><small>{metric.label === "Monthly revenue" ? "$108k target" : metric.label === "Cash runway" ? "12 mo threshold" : "$485k target"}</small></article>)}</section>
    <div className="dashboard-grid">
      <section className="panel insights-panel"><div className="panel-header"><div><span className="eyebrow coral">DECISION QUEUE</span><h2>Needs your attention</h2></div><span className="count-badge">{pending.length} open</span></div><div className="insight-list">{data.insights.slice(0,2).map((insight) => <article className={`insight ${insight.status}`} key={insight.id}><span className={`severity ${insight.severity}`}>{insight.severity === "critical" ? "!" : "△"}</span><div><div className="insight-title"><h3>{insight.title}</h3><span className={insight.severity}>{insight.severity}</span></div><p>{insight.detail}</p><div className="insight-actions">{insight.status === "approved" ? <span className="approved-mark">✓ Approved and added to plan</span> : <><button className="action-button" onClick={() => approve(insight.id)} disabled={loadingId === insight.id}>{loadingId === insight.id ? "Applying…" : insight.action}</button><button className="text-button">View context</button></>}</div></div></article>)}</div></section>
      <section className="panel goals-panel"><div className="panel-header"><div><span className="eyebrow blue">EXECUTION</span><h2>Company priorities</h2></div><button className="text-button">View all →</button></div><div className="initiative-list">{data.initiatives.slice(0,3).map((item) => <article className="initiative" key={item.id}><div className="initiative-title"><span className="avatar mini">{item.owner[0]}</span><div><h3>{item.title}</h3><p>{item.team} · {item.owner}</p></div><em className={item.status === "At risk" ? "at-risk" : "on-track"}>{item.status}</em></div><div className="initiative-progress"><div className="progress-track"><i style={{ width: `${item.progress}%` }}/></div><span>{item.progress}%</span><small>{item.due}</small></div></article>)}</div></section>
      <section className="panel ask-panel"><div className="ask-heading"><div className="ai-orb small-orb">✦</div><div><span className="eyebrow violet">ASK YOUR STARTUP</span><h2>One answer, across every team.</h2></div></div>{answer ? <div className="answer-box"><span>✦</span><p>{answer}</p></div> : <div className="suggestions"><button onClick={() => setQuery("What is our biggest risk?")}>What is our biggest risk?</button><button onClick={() => setQuery("How is revenue trending?")}>How is revenue trending?</button><button onClick={() => setQuery("Where is team capacity tight?")}>Where is team capacity tight?</button></div>}<form className="ask-form" onSubmit={ask}><input id="ask-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ask about revenue, runway, goals, or blockers…" aria-label="Ask Northstar"/><button aria-label="Send question">↑</button></form></section>
    </div>
  </>;
}

type WorkspaceRecord = { id:string; type:string; title:string; subtitle:string; status:string; value:string; progress:number; owner:string };
type WorkspacePayload = { session:{organization:{name:string};role:"owner"|"member"}; records:WorkspaceRecord[] };

function ModulePage({ active, data, user }: { active: string; data: DashboardData; user:{name:string;email:string} }) {
  const [workspace,setWorkspace]=useState<WorkspacePayload|null>(null);
  const [showCreate,setShowCreate]=useState(false);
  const [saving,setSaving]=useState(false);
  const [moduleError,setModuleError]=useState("");
  const [form,setForm]=useState({title:"",subtitle:"",value:""});
  const authHeaders={"x-demo-email":user.email,"x-demo-name":user.name};
  useEffect(()=>{fetch("/api/workspace",{headers:authHeaders}).then(async response=>{if(!response.ok)throw new Error((await response.json()).error||"Unable to load workspace");return response.json() as Promise<WorkspacePayload>;}).then(setWorkspace).catch(error=>setModuleError(error instanceof Error?error.message:"Unable to load workspace"));},[user.email,user.name]);
  const type=active==="Goals"?"goal":active==="CRM"?"deal":active==="Team"?"role":"report";
  const config: Record<string, { eyebrow:string; title:string; copy:string; singular:string; defaultStatus:string }> = {
    Goals:{eyebrow:"STRATEGY & EXECUTION",title:"Every priority, clearly owned.",copy:"Connect company goals to initiatives, owners, and measurable outcomes.",singular:"goal",defaultStatus:"Planned"},
    CRM:{eyebrow:"GROWTH PIPELINE",title:`${data.metrics[2]?.value||"Pipeline"} in active opportunities.`,copy:"Focus the team on the deals with the strongest intent and clearest next action.",singular:"deal",defaultStatus:"Qualified"},
    Team:{eyebrow:"PEOPLE & CAPACITY",title:"Build without burning out.",copy:"See workload, hiring progress, and capacity risks before they slow execution.",singular:"role",defaultStatus:"Open"},
    Reports:{eyebrow:"AUTOMATED REPORTING",title:"Your operating review is ready.",copy:"Turn live company data into a clear weekly update for your team and investors.",singular:"report",defaultStatus:"Draft"},
  };
  const item=config[active],records=workspace?.records.filter(record=>record.type===type)||[];
  async function mutate(method:"POST"|"PATCH"|"DELETE",body:Record<string,unknown>){setSaving(true);setModuleError("");try{const response=await fetch("/api/workspace",{method,headers:{"Content-Type":"application/json",...authHeaders},body:JSON.stringify(body)});const payload=await response.json() as WorkspacePayload&{error?:string};if(!response.ok)throw new Error(payload.error||"Unable to save record");setWorkspace(payload);return true;}catch(error){setModuleError(error instanceof Error?error.message:"Unable to save record");return false;}finally{setSaving(false);}}
  async function create(event:React.FormEvent){event.preventDefault();if(!form.title.trim())return;const ok=await mutate("POST",{type,title:form.title,subtitle:form.subtitle||`New ${item.singular}`,value:form.value||"—",status:item.defaultStatus,progress:0});if(ok){setForm({title:"",subtitle:"",value:""});setShowCreate(false);}}
  return <>
    <section className="page-heading module-heading"><div><span className="eyebrow">{item.eyebrow}</span><h1>{item.title}</h1><p>{workspace?.session.organization.name||item.copy} · {item.copy}</p></div><button className="primary-button" onClick={()=>setShowCreate(true)}>+ Create {item.singular}</button></section>
    <section className="module-hero"><div className="module-visual"><span className="ring ring-one"/><span className="ring ring-two"/><div className="module-score"><small>LIVE RECORDS</small><strong>{workspace?records.length:"—"}</strong><p>{item.singular}s in this company workspace</p></div></div><div className="module-summary"><span className="eyebrow violet">TENANT-SAFE WORKSPACE</span><h2>{active==="CRM"?"Move qualified demand toward revenue.":active==="Team"?"Keep hiring connected to capacity.":active==="Reports"?"Turn operating data into decisions.":"Keep execution tied to outcomes."}</h2><p>Every record is saved to your company workspace and protected by server-side membership and role checks.</p><span className="role-pill">{workspace?.session.role||"loading"} access</span></div></section>
    <section className="panel module-table"><div className="panel-header"><div><span className="eyebrow blue">LIVE DATABASE</span><h2>{records.length} {item.singular}{records.length===1?"":"s"}</h2></div><span className="save-state">{saving?"Saving…":"All changes saved"}</span></div>{moduleError?<div className="module-error">{moduleError}</div>:null}{!workspace?<div className="module-empty">Loading your workspace…</div>:records.length===0?<div className="module-empty">No {item.singular}s yet. Create the first one.</div>:records.map(record=><div className="record-row" key={record.id}><span className={`record-icon ${type}`}>{type==="goal"?"◎":type==="deal"?"↗":type==="role"?"◌":"▤"}</span><div className="record-copy"><b>{record.title}</b><small>{record.subtitle} · {record.owner}</small></div><span className="table-progress"><i style={{width:`${record.progress}%`}}/></span><em>{record.value}</em><button className="status-button" onClick={()=>mutate("PATCH",{id:record.id,status:record.status==="Complete"?item.defaultStatus:"Complete",progress:record.status==="Complete"?50:100})}>{record.status}</button>{workspace.session.role==="owner"?<button className="delete-button" onClick={()=>mutate("DELETE",{id:record.id})} aria-label={`Delete ${record.title}`}>×</button>:null}</div>)}</section>
    {showCreate?<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowCreate(false)}><form className="create-modal" onSubmit={create} onMouseDown={event=>event.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow coral">NEW {item.singular.toUpperCase()}</span><h2>Create {item.singular}</h2></div><button type="button" onClick={()=>setShowCreate(false)}>×</button></div><label>Title<input autoFocus value={form.title} onChange={event=>setForm({...form,title:event.target.value})} placeholder={`Name this ${item.singular}`} required/></label><label>Description<input value={form.subtitle} onChange={event=>setForm({...form,subtitle:event.target.value})} placeholder="Add useful context"/></label><label>{type==="deal"?"Deal value":"Target or label"}<input value={form.value} onChange={event=>setForm({...form,value:event.target.value})} placeholder={type==="deal"?"$25k":"Q3"}/></label><div className="modal-actions"><button type="button" className="cancel-button" onClick={()=>setShowCreate(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Creating…":`Create ${item.singular}`}</button></div></form></div>:null}
  </>;
}

type NetworkPayload={profile:{name:string;email:string;headline:string;location:string;bio:string;skills:string;resume_name:string};people:Array<{id:string;name:string;email:string;headline?:string;location?:string;skills?:string;connection_status:string}>};
const demoHeaders=(user:{name:string;email:string})=>({"x-demo-email":user.email,"x-demo-name":user.name});

type FeedPost={id:string;content:string;created_at:string;name:string;email:string;likes:number;liked:number;comments:Array<{id:string;content:string;created_at:string;name:string}>};
function FeedPage({user}:{user:{name:string;email:string}}){
  const [posts,setPosts]=useState<FeedPost[]>([]),[draft,setDraft]=useState(""),[comments,setComments]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[feedError,setFeedError]=useState("");
  async function request(body?:Record<string,unknown>){setBusy(true);setFeedError("");try{const response=await fetch("/api/feed",{method:body?"POST":"GET",headers:{...(body?{"Content-Type":"application/json"}:{}),...demoHeaders(user)},body:body?JSON.stringify(body):undefined});const payload=await response.json() as {posts?:FeedPost[];error?:string};if(!response.ok)throw new Error(payload.error||"Unable to load the company feed");setPosts(payload.posts||[]);return true;}catch(error){setFeedError(error instanceof Error?error.message:"Unable to load the company feed");return false;}finally{setBusy(false)}}
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{void request();},[user.email,user.name]);
  async function publish(event:React.FormEvent){event.preventDefault();if(!draft.trim())return;if(await request({content:draft.trim()}))setDraft("");}
  async function addComment(event:React.FormEvent,postId:string){event.preventDefault();const content=comments[postId]?.trim();if(!content)return;if(await request({action:"comment",postId,content}))setComments({...comments,[postId]:""});}
  return <><section className="page-heading"><div><span className="eyebrow coral">COMPANY FEED</span><h1>Work in public. Move together.</h1><p>Share decisions, progress, customer learning, blockers, and wins with your company.</p></div><span className="feed-scope">Private to your workspace</span></section><div className="feed-layout"><section className="feed-main"><form className="post-composer" onSubmit={publish}><span className="avatar">{user.name.slice(0,2).toUpperCase()}</span><div><textarea value={draft} onChange={event=>setDraft(event.target.value)} maxLength={2000} placeholder="Share an update, decision, question, or win…"/><div className="composer-footer"><span>{draft.length}/2000</span><button className="primary-button" disabled={busy||!draft.trim()}>{busy?"Publishing…":"Post update"}</button></div></div></form>{feedError?<div className="module-error">{feedError}</div>:null}{posts.length===0&&!busy?<div className="feed-empty"><b>Start the company conversation</b><p>Post today’s priority or a decision your team should know.</p></div>:posts.map(post=><article className="feed-post" key={post.id}><header><span className="avatar">{post.name.slice(0,2).toUpperCase()}</span><div><b>{post.name}</b><small>{post.email} · {new Date(post.created_at).toLocaleString()}</small></div><em>Team update</em></header><p className="post-content">{post.content}</p><div className="post-stats"><span>{post.likes} {Number(post.likes)===1?"like":"likes"}</span><span>{post.comments.length} {post.comments.length===1?"comment":"comments"}</span></div><div className="post-actions"><button className={post.liked?"liked":""} onClick={()=>request({action:"like",postId:post.id})}>{post.liked?"♥ Liked":"♡ Like"}</button><button onClick={()=>document.getElementById(`comment-${post.id}`)?.focus()}>Comment</button></div>{post.comments.length?<div className="comment-list">{post.comments.map(comment=><div key={comment.id}><span>{comment.name.slice(0,2).toUpperCase()}</span><p><b>{comment.name}</b>{comment.content}</p></div>)}</div>:null}<form className="comment-form" onSubmit={event=>addComment(event,post.id)}><span>{user.name.slice(0,2).toUpperCase()}</span><input id={`comment-${post.id}`} value={comments[post.id]||""} onChange={event=>setComments({...comments,[post.id]:event.target.value})} placeholder="Add a thoughtful comment…"/><button disabled={busy}>Send</button></form></article>)}</section><aside className="feed-aside"><article><span className="eyebrow violet">POSTING RHYTHM</span><h3>Keep updates actionable</h3><ul><li><b>Decision:</b> what changed and why</li><li><b>Progress:</b> result versus target</li><li><b>Blocker:</b> owner and help needed</li><li><b>Learning:</b> evidence from customers</li></ul></article><article><span className="eyebrow blue">THIS WEEK</span><strong>{posts.length}</strong><p>company updates shared</p></article></aside></div></>;
}

type TeamPayload={session:{role:"owner"|"admin"|"member"|"viewer";organization:{name:string}};members:Array<{id:string;name:string;email:string;role:string;created_at:string}>;invites:Array<{id:string;email:string;role:string;status:string;created_at:string}>};
function TeamAccessPage({user}:{user:{name:string;email:string}}){
  const [data,setData]=useState<TeamPayload|null>(null),[email,setEmail]=useState(""),[role,setRole]=useState("member"),[teamError,setTeamError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  async function request(body?:Record<string,unknown>){setBusy(true);setTeamError("");try{const response=await fetch("/api/team-access",{method:body?"POST":"GET",headers:{...(body?{"Content-Type":"application/json"}:{}),...demoHeaders(user)},body:body?JSON.stringify(body):undefined});const payload=await response.json() as TeamPayload&{error?:string};if(!response.ok)throw new Error(payload.error||"Unable to update team access");setData(payload);return true;}catch(error){setTeamError(error instanceof Error?error.message:"Unable to update team access");return false;}finally{setBusy(false)}}
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{void request();},[user.email,user.name]);
  async function inviteMember(event:React.FormEvent){event.preventDefault();if(!email.trim())return;if(await request({email:email.trim(),role})){setNotice(`Invitation created for ${email.trim()}. They will join when they sign in with this email.`);setEmail("");}}
  const canInvite=data&&["owner","admin"].includes(data.session.role);
  return <><section className="page-heading"><div><span className="eyebrow blue">TEAM & ACCESS</span><h1>Give every teammate the right context.</h1><p>Invite your team, assign clear access, and keep company information protected.</p></div><span className="role-pill">{data?.session.role||"loading"} access</span></section>{teamError?<div className="module-error">{teamError}</div>:null}{notice?<div className="team-notice">✓ {notice}</div>:null}<section className="access-grid"><article className="invite-card"><span className="eyebrow coral">INVITE TEAMMATE</span><h2>Grow your workspace</h2><p>Use the same email your teammate will use to sign in.</p><form onSubmit={inviteMember}><label>Work email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="teammate@company.com" required disabled={!canInvite}/></label><label>Access level<select value={role} onChange={event=>setRole(event.target.value)} disabled={!canInvite}><option value="admin">Team leader · manage members</option><option value="member">Member · create and collaborate</option><option value="viewer">Viewer · read and comment</option></select></label><button className="primary-button" disabled={!canInvite||busy}>{busy?"Sending…":"Create invitation"}</button>{data&&!canInvite?<small>Ask an owner or team leader to invite people.</small>:null}</form></article><article className="permission-card"><span className="eyebrow violet">ACCESS MODEL</span><h2>Simple, accountable roles</h2>{[["Owner","Full control, billing and roles"],["Team leader","Invite people and manage work"],["Member","Create, update, post and comment"],["Viewer","Read, like and comment"]].map(([name,copy])=><div key={name}><b>{name}</b><p>{copy}</p></div>)}</article></section><section className="panel members-panel"><div className="panel-header"><div><span className="eyebrow blue">ACTIVE TEAM</span><h2>{data?.members.length||0} workspace members</h2></div><span>{data?.session.organization.name}</span></div>{data?.members.map(member=><div className="member-row" key={member.id}><span className="avatar">{member.name.slice(0,2).toUpperCase()}</span><div><b>{member.name}</b><small>{member.email}</small></div>{data.session.role==="owner"&&member.role!=="owner"?<select value={member.role} onChange={event=>request({userId:member.id,role:event.target.value})}><option value="admin">Team leader</option><option value="member">Member</option><option value="viewer">Viewer</option></select>:<span className="member-role">{member.role}</span>}</div>)}</section>{data?.invites.length?<section className="panel invite-list"><div className="panel-header"><div><span className="eyebrow coral">INVITATIONS</span><h2>Invitation history</h2></div></div>{data.invites.map(invite=><div key={invite.id}><span>{invite.email}</span><b>{invite.role}</b><em className={invite.status}>{invite.status}</em></div>)}</section>:null}</>;
}

function PeoplePage({user}:{user:{name:string;email:string}}){
  const [data,setData]=useState<NetworkPayload|null>(null),[query,setQuery]=useState(""),[error,setError]=useState("");
  const load=()=>fetch("/api/people",{headers:demoHeaders(user)}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);return body as NetworkPayload}).then(setData).catch(e=>setError(e.message));
  useEffect(load,[user.email,user.name]);
  async function connectPerson(id:string){const r=await fetch("/api/people",{method:"POST",headers:{"Content-Type":"application/json",...demoHeaders(user)},body:JSON.stringify({recipientId:id})});const body=await r.json();if(r.ok)setData(body);else setError(body.error);}
  const people=data?.people.filter(p=>`${p.name} ${p.headline||""} ${p.location||""}`.toLowerCase().includes(query.toLowerCase()))||[];
  return <><section className="page-heading people-heading"><div><span className="eyebrow coral">PEOPLE NETWORK</span><h1>Find the people who move ideas forward.</h1><p>A trusted founder network, built into your operating system.</p></div><div className="network-count"><b>{data?.people.filter(p=>p.connection_status==="connected").length||0}</b><span>connections</span></div></section><section className="people-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, role, or location…"/><button>Discover people</button></section>{error?<div className="module-error">{error}</div>:null}<section className="people-grid">{people.map((person,index)=><article className="person-card" key={person.id}><div className={`person-cover cover-${index%4}`}><span>{person.name.split(" ").map(n=>n[0]).join("")}</span></div><div className="person-body"><h3>{person.name}</h3><p>{person.headline||["Product leader","Growth strategist","Founding engineer","Design systems lead"][index%4]}</p><small>⌖ {person.location||["San Francisco","Bengaluru","Seoul","London"][index%4]}</small><div className="skill-row">{(person.skills||["Strategy,Product","Growth,GTM","Engineering,AI","Design,Systems"][index%4]).split(",").slice(0,2).map(skill=><span key={skill}>{skill}</span>)}</div><button className={person.connection_status==="connected"?"connected":""} onClick={()=>connectPerson(person.id)} disabled={person.connection_status==="connected"}>{person.connection_status==="connected"?"✓ Connected":"＋ Connect"}</button></div></article>)}</section></>;
}

function SettingsPage({user,onSaved}:{user:{name:string;email:string};onSaved:(u:{name:string;email:string})=>void}){
  const [form,setForm]=useState({name:user.name,email:user.email,headline:"Founder & CEO",location:"Bengaluru, India",bio:"Building thoughtful products and high-agency teams.",skills:"Strategy, Product, Fundraising"});
  const [resume,setResume]=useState(""),[status,setStatus]=useState(""),[tab,setTab]=useState("Profile");
  useEffect(()=>{fetch("/api/people",{headers:demoHeaders(user)}).then(r=>r.json()).then((d:NetworkPayload)=>{if(d.profile){setForm({...form,...d.profile,name:d.profile.name||user.name,email:user.email});setResume(d.profile.resume_name||"");}}).catch(()=>{});},[user.email]);
  async function save(e:React.FormEvent){e.preventDefault();setStatus("Saving…");const r=await fetch("/api/people",{method:"PATCH",headers:{"Content-Type":"application/json",...demoHeaders(user)},body:JSON.stringify(form)});if(r.ok){onSaved({name:form.name,email:user.email});setStatus("Changes saved");}else setStatus("Could not save changes");}
  async function upload(file?:File){if(!file)return;setStatus("Uploading résumé…");const body=new FormData();body.append("resume",file);const r=await fetch("/api/resume",{method:"POST",headers:demoHeaders(user),body});const data=await r.json();if(r.ok){setResume(data.name);setStatus("Résumé uploaded");}else setStatus(data.error);}
  return <><section className="page-heading"><div><span className="eyebrow blue">WORKSPACE SETTINGS</span><h1>Make Northstar yours.</h1><p>Manage your public identity, documents, and workspace preferences.</p></div></section><div className="settings-layout"><aside className="settings-nav">{["Profile","Documents","Appearance","Security"].map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</aside><section className="settings-card">{tab==="Profile"?<form onSubmit={save}><div className="profile-editor-head"><span className="profile-photo">{form.name.slice(0,2).toUpperCase()}</span><div><h2>Public profile</h2><p>This is how founders and collaborators see you.</p></div></div><div className="form-grid"><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input value={form.email} disabled/></label><label className="wide">Professional headline<input value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})}/></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Skills<input value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})}/></label><label className="wide">About<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></label></div><button className="primary-button">Save profile</button></form>:tab==="Documents"?<div><h2>Résumé & documents</h2><p>Upload your résumé so collaborators can understand your experience.</p><label className="resume-drop"><input type="file" accept=".pdf,.doc,.docx" onChange={e=>upload(e.target.files?.[0])}/><span>⇧</span><b>{resume||"Drop your résumé here"}</b><small>PDF, DOC, or DOCX · Maximum 5 MB</small></label></div>:tab==="Appearance"?<div><h2>Appearance</h2><p>Northstar follows your saved light or dark theme preference.</p><button className="primary-button" onClick={()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("northstar-theme",next);}}>Toggle light / dark</button></div>:<div><h2>Demo account security</h2><p>This hackathon build uses device-local demo sessions. Production identity can be connected before launch.</p><div className="security-note">Your workspace data remains stored in the application database. Never use a real password in this demo.</div></div>}{status?<p className="save-message">{status}</p>:null}</section></div></>;
}

type LiveAgentResult={score:string;confidence:number;title:string;summary:string;items:string[];evidence:string[];assumptions:string[];risks:string[];metrics:Array<{label:string;value:string;source:string}>;mode:"live"|"demo";runId:string};
function IntelligenceModule({active,user}:{active:string;user:{name:string;email:string}}){
  const [input,setInput]=useState(""),[result,setResult]=useState<LiveAgentResult|null>(null),[running,setRunning]=useState(false),[approved,setApproved]=useState<string[]>([]),[agentError,setAgentError]=useState("");
  const configs:Record<string,{kicker:string;title:string;copy:string;placeholder:string;action:string;color:string}>= {
    "Idea Validation":{kicker:"IDEA VALIDATION ENGINE",title:"Turn assumptions into evidence.",copy:"Score demand, differentiation, feasibility, and business potential before committing resources.",placeholder:"Describe your startup idea, customer, problem, and proposed solution…",action:"Validate idea",color:"plum"},
    "AI Mediation":{kicker:"AI MEDIATION AGENT",title:"Resolve tension without losing momentum.",copy:"Structure disagreements, surface shared interests, and create a neutral action plan for the team.",placeholder:"Describe the disagreement, the people involved, and the decision that is blocked…",action:"Start mediation",color:"teal"},
    "Governance Agents":{kicker:"AUTONOMOUS GOVERNANCE AGENTS",title:"Continuous oversight, clear accountability.",copy:"Specialized agents monitor finance, compliance, delivery, and people risk—then propose auditable actions.",placeholder:"Ask the governance council to review a decision or company risk…",action:"Run council review",color:"coral"},
    "Financial Dashboard":{kicker:"REAL-TIME FINANCIAL DASHBOARD",title:"Know your position before the meeting.",copy:"Monitor revenue, burn, runway, cash flow, and forecast variance from one operating view.",placeholder:"Ask a finance question, such as “Can we afford two new hires?”…",action:"Run scenario",color:"blue"},
    "Term Sheet Analyzer":{kicker:"AI TERM SHEET ANALYZER",title:"Understand the deal behind the headline.",copy:"Review economics, control terms, dilution, investor protections, and founder risk in plain language.",placeholder:"Paste term-sheet clauses or summary terms here for analysis…",action:"Analyze terms",color:"amber"}
  };
  const c=configs[active];
  async function run(){if(!input.trim())return;setRunning(true);setAgentError("");setResult(null);try{const response=await fetch("/api/agents",{method:"POST",headers:{"Content-Type":"application/json",...demoHeaders(user)},body:JSON.stringify({agent:active,input})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Agent failed");setResult(body);}catch(error){setAgentError(error instanceof Error?error.message:"Agent failed");}finally{setRunning(false)}}
  async function approveRun(){if(!result)return;const response=await fetch("/api/agents",{method:"POST",headers:{"Content-Type":"application/json",...demoHeaders(user)},body:JSON.stringify({approveRunId:result.runId})});if(response.ok)setApproved([...approved,result.runId]);}
  const agents=[{name:"Finance Guardian",detail:"Burn variance is 4.2% below plan",risk:"Healthy"},{name:"Compliance Sentinel",detail:"One policy review due in 9 days",risk:"Review"},{name:"Delivery Steward",detail:"Enterprise launch needs an owner",risk:"Action"},{name:"People Advocate",detail:"Platform capacity risk next sprint",risk:"Review"}];
  return <><section className={`intelligence-hero ${c.color}`}><div><span>{c.kicker}</span><h1>{c.title}</h1><p>{c.copy}</p></div><div className="agent-pulse"><i/><b>Agent online</b><small>Context synced now</small></div></section>
    {active==="Governance Agents"?<section className="agent-grid">{agents.map(a=><article key={a.name}><div className="agent-symbol">⬡</div><div><h3>{a.name}</h3><p>{a.detail}</p></div><span className={a.risk.toLowerCase()}>{a.risk}</span><button onClick={()=>setApproved([...approved,a.name])} disabled={approved.includes(a.name)}>{approved.includes(a.name)?"Approved":"Review action"}</button></article>)}</section>:null}
    {active==="Financial Dashboard"?<section className="finance-strip"><article><small>Monthly recurring revenue</small><b>$84,240</b><em>+12.4%</em></article><article><small>Net burn</small><b>$41,800</b><em className="neutral">−3.1%</em></article><article><small>Runway</small><b>14.2 mo</b><em>+0.8 mo</em></article><article><small>Cash balance</small><b>$593,400</b><em className="live">● live</em></article></section>:null}
    <section className="agent-workbench"><div className="workbench-main"><div className="workbench-heading"><span className="eyebrow">AGENT WORKSPACE</span><h2>{active==="Term Sheet Analyzer"?"Paste or upload your terms":active==="Idea Validation"?"Describe the opportunity":"Brief the agent"}</h2><p>For the most accurate report, include numbers, dates, stakeholders, constraints, and the decision you need to make.</p></div><textarea value={input} onChange={e=>{setInput(e.target.value);setResult(null)}} placeholder={c.placeholder}/>{active==="Term Sheet Analyzer"?<label className="inline-upload"><input type="file" accept=".pdf,.doc,.docx,.txt" onChange={e=>setInput(`Uploaded: ${e.target.files?.[0]?.name||"term sheet"}\n$8m pre-money valuation, 1x non-participating liquidation preference, broad-based weighted average anti-dilution.`)}/>⇧ Upload term sheet</label>:null}<button className="primary-button" onClick={run} disabled={!input.trim()||running}>{running?"Agents are working…":c.action}</button></div><aside className="agent-context"><span className="eyebrow">CONNECTED CONTEXT</span>{["Company goals","Financial model","Team capacity","CRM pipeline"].map(item=><div key={item}><i>✓</i><span><b>{item}</b><small>Synced</small></span></div>)}</aside></section>
    {agentError?<div className="module-error">{agentError}</div>:null}{result?<AnalysisResult result={result} approved={approved.includes(result.runId)} onApprove={approveRun}/>:null}</>;
}

function AnalysisResult({result,onApprove,approved}:{result:LiveAgentResult;onApprove:()=>void;approved:boolean}){
  return <section className="detailed-analysis"><header><div className="analysis-score"><b>{result.score}</b><small>{result.confidence}% confidence</small></div><div><span className="eyebrow mint">ANALYSIS COMPLETE · {result.mode.toUpperCase()}</span><h2>{result.title}</h2><p>{result.summary}</p></div><button onClick={onApprove} disabled={approved}>{approved?"✓ Approved":"Approve action plan"}</button></header><div className="evidence-metrics">{result.metrics.map(m=><article key={m.label}><small>{m.label}</small><b>{m.value}</b><span>{m.source}</span></article>)}</div><div className="report-columns"><article><h3>Evidence</h3>{result.evidence.map(i=><p key={i}>✓ {i}</p>)}</article><article><h3>Assumptions</h3>{result.assumptions.map(i=><p key={i}>◇ {i}</p>)}</article><article><h3>Risks & gaps</h3>{result.risks.map(i=><p key={i}>△ {i}</p>)}</article></div><div className="recommended-actions"><h3>Recommended actions</h3><ol>{result.items.map(i=><li key={i}>{i}</li>)}</ol></div><footer>Every statement is labeled by source type. Verify important financial, legal, and people decisions with qualified professionals.</footer></section>;
}
