import { env } from "cloudflare:workers";
import type { WorkspaceSession } from "./workspace";
const db=()=>env.DB,now=()=>new Date().toISOString(),id=(p:string)=>`${p}_${crypto.randomUUID()}`;
export async function ensureCollaboration(){await db().batch([
  db().prepare("CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, author_id TEXT NOT NULL, organization_id TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT NOT NULL)"),
  db().prepare("CREATE TABLE IF NOT EXISTS post_likes (post_id TEXT NOT NULL, user_id TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(post_id,user_id))"),
  db().prepare("CREATE TABLE IF NOT EXISTS post_comments (id TEXT PRIMARY KEY, post_id TEXT NOT NULL, author_id TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT NOT NULL)"),
  db().prepare("CREATE TABLE IF NOT EXISTS team_invites (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, inviter_id TEXT NOT NULL, email TEXT NOT NULL, role TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL)"),
  db().prepare("CREATE INDEX IF NOT EXISTS posts_created_idx ON posts(created_at)"),
]);}
export async function feed(session:WorkspaceSession){await ensureCollaboration();const posts=await db().prepare("SELECT p.id,p.content,p.created_at,u.name,u.email,(SELECT COUNT(*) FROM post_likes l WHERE l.post_id=p.id) likes,EXISTS(SELECT 1 FROM post_likes l WHERE l.post_id=p.id AND l.user_id=?) liked FROM posts p JOIN users u ON u.id=p.author_id WHERE p.organization_id=? ORDER BY p.created_at DESC LIMIT 30").bind(session.user.id,session.organization.id).all<Record<string,unknown>>();for(const post of posts.results){const comments=await db().prepare("SELECT c.id,c.content,c.created_at,u.name FROM post_comments c JOIN users u ON u.id=c.author_id WHERE c.post_id=? ORDER BY c.created_at").bind(post.id).all();post.comments=comments.results;}return {posts:posts.results};}
export async function createPost(session:WorkspaceSession,content:string){await ensureCollaboration();if(session.role==="viewer")throw new Error("Viewer access cannot publish posts");await db().prepare("INSERT INTO posts (id,author_id,organization_id,content,created_at) VALUES (?,?,?,?,?)").bind(id("post"),session.user.id,session.organization.id,content,now()).run();}
async function visiblePost(session:WorkspaceSession,postId:string){return db().prepare("SELECT id FROM posts WHERE id=? AND organization_id=?").bind(postId,session.organization.id).first();}
export async function toggleLike(session:WorkspaceSession,postId:string){await ensureCollaboration();if(!(await visiblePost(session,postId)))throw new Error("Post not found");const found=await db().prepare("SELECT post_id FROM post_likes WHERE post_id=? AND user_id=?").bind(postId,session.user.id).first();if(found)await db().prepare("DELETE FROM post_likes WHERE post_id=? AND user_id=?").bind(postId,session.user.id).run();else await db().prepare("INSERT INTO post_likes (post_id,user_id,created_at) VALUES (?,?,?)").bind(postId,session.user.id,now()).run();}
export async function comment(session:WorkspaceSession,postId:string,content:string){await ensureCollaboration();if(!(await visiblePost(session,postId)))throw new Error("Post not found");await db().prepare("INSERT INTO post_comments (id,post_id,author_id,content,created_at) VALUES (?,?,?,?,?)").bind(id("comment"),postId,session.user.id,content,now()).run();}
export async function team(session:WorkspaceSession){await ensureCollaboration();const members=await db().prepare("SELECT u.id,u.name,u.email,m.role,m.created_at FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=? ORDER BY m.created_at").bind(session.organization.id).all();const invites=await db().prepare("SELECT id,email,role,status,created_at FROM team_invites WHERE organization_id=? ORDER BY created_at DESC").bind(session.organization.id).all();return {session,members:members.results,invites:invites.results};}
export async function invite(session:WorkspaceSession,email:string,role:string){if(!["owner","admin"].includes(session.role))throw new Error("Only team leaders can invite members");if(!["admin","member","viewer"].includes(role))throw new Error("Invalid access role");await ensureCollaboration();const existing=await db().prepare("SELECT id FROM team_invites WHERE organization_id=? AND email=? AND status='pending'").bind(session.organization.id,email.toLowerCase()).first();if(existing)throw new Error("An invitation is already pending for this email");await db().prepare("INSERT INTO team_invites (id,organization_id,inviter_id,email,role,status,created_at) VALUES (?,?,?,?,?,?,?)").bind(id("invite"),session.organization.id,session.user.id,email.toLowerCase(),role,"pending",now()).run();}
export async function updateMemberRole(session:WorkspaceSession,userId:string,role:string){if(session.role!=="owner")throw new Error("Only the team owner can change access");if(!["admin","member","viewer"].includes(role))throw new Error("Invalid access role");if(userId===session.user.id)throw new Error("The workspace owner role cannot be changed");await db().prepare("UPDATE memberships SET role=? WHERE user_id=? AND organization_id=?").bind(role,userId,session.organization.id).run();}
