import postgres from "postgres";
let client:ReturnType<typeof postgres>|null=null;
function sqlClient(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL;if(!url)throw new Error("DATABASE_URL is not configured");client??=postgres(url,{ssl:"require",max:5,idle_timeout:20});return client;}
function convert(source:string){let index=0;return source.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/gi,"INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY").replace(/\?/g,()=>`$${++index}`);}
export class RuntimeStatement{constructor(private source:string,private values:unknown[]=[]){ }bind(...values:unknown[]){return new RuntimeStatement(this.source,values);}private execute(){return sqlClient().unsafe(convert(this.source),this.values as never[]);}async run(){const rows=await this.execute();return{success:true,meta:{changes:rows.count}};}async all<T=Record<string,unknown>>(){const rows=await this.execute();return{results:[...rows] as T[]};}async first<T=Record<string,unknown>>(){const rows=await this.execute();return(rows[0] as T|undefined)??null;}}
export const database={
  prepare:(source:string)=>new RuntimeStatement(source),
  batch:async(statements:RuntimeStatement[])=>{
    const results=[];
    for(const statement of statements)results.push(await statement.run());
    return results;
  },
};
